[env:transmitter]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = +<transmitter.cpp>

[env:receiver]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = +<receiver.cpp>

[env:messenger]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = +<messenger.cpp>
lib_deps =
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.3.23
    bblanchon/ArduinoJson@^7.0.0
lib_ignore =
    ESPAsyncTCP
    AsyncTCP_RP2040W
